### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dista** [RReverser/WiFi-Password#5]
PS C:\Users\xxx> WiFi-Password

SSID       : XXX
Password   :
Auth type  :

No password is showed

**Comment by wuminorb** [comment]
same problem

**Comment by RReverser** [comment]
Not helpful without details about machine / Wi-Fi / etc..

**Comment by dista** [comment]
Win10 enterprise
802.11n 
WPA2-Personal 
Intel(R) Dual Band Wireless-AC 7260

**Comment by qq915458022** [comment]
# Same Problem
![doesnwork](https://dl.ifengge.cn/mcpesa/wifi_password_not_working.png)

## System
- Windows 10 enterprise Insider Preview 14295 (x64) - (Chinese-Simplified) 
- WPA2-Personal 

## Other Information
![Others](https://dl.ifengge.cn/mcpesa/adapter.png "Other Information")
