### ISSUE TITLE
Debian version

### ISSUE THREAD

**Issue by Sliicy** [RReverser/WiFi-Password#8]
You didn't support Debian Linux! So I made a Debian Variant for wifi-password here:
https://github.com/Sliicy/wifipassword
The code (if you can please add to this repo to make it more complete):
```bash
#!/bin/bash

WIFI="$(iwgetid -r)"
#Create a variable called "WIFI" equal to the name of the current Network.

echo ${WIFI}
#Print out the Wi-Fi Name.

awk '/psk=/{print $NF}' /etc/NetworkManager/system-connections/${WIFI} | cut -c 5-
#Print out the saved password of this wifi and trim the results (so you don't see "psk=").
```

**Comment by notpushkin** [comment]
Here's my take on it, also printing a QR for easier connection :) https://gist.github.com/notpushkin/7872a22a39f33a3394635df3bd2a0c4d
